[package]
name = "card-generator"
version = "1.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[profile.release]
# v This is now used by default, if not provided
strip = "debuginfo"
